# -*- coding: utf-8 -*-

# -*- coding: utf-8 -*
'''
#---Project--------------: PM1200监护仪，通过串口获取设备PM1200
#------------------------: 上传的血氧、血压、心电、体温等数据，
#------------------------: 上位机进行数据展示、波形绘制与开关操作
#----------------------------------------------------------------
#---DocumentDescription--: 实现上位机的布局和部件属性设置
#----------------------------------------------------------------
#---CreateTime-----------: 2019.10.1
#---By-------------------: luoshutu
'''

from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg
import PM1200Parameter as PMPar

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1322, 845)
        MainWindow.setFont(QtGui.QFont('Times New Roman',10))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(9, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainLayout = QtWidgets.QGridLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.layoutValue = QtWidgets.QGridLayout()
        self.layoutValue.setObjectName("layoutValue")
        self.TextBrowserSPO2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.TextBrowserSPO2.setMaximumSize(QtCore.QSize(200, 30))
        self.TextBrowserSPO2.setObjectName("TextBrowserSPO2")
        self.layoutValue.addWidget(self.TextBrowserSPO2, 0, 1, 1, 1)
        self.labelPR = QtWidgets.QLabel(self.centralwidget)
        self.labelPR.setObjectName("labelPR")
        self.layoutValue.addWidget(self.labelPR, 1, 0, 1, 1)
        self.TextBrowserPR = QtWidgets.QTextBrowser(self.centralwidget)
        self.TextBrowserPR.setMaximumSize(QtCore.QSize(200, 30))
        self.TextBrowserPR.setObjectName("TextBrowserPR")
        self.layoutValue.addWidget(self.TextBrowserPR, 1, 1, 1, 1)
        self.labelCuff = QtWidgets.QLabel(self.centralwidget)
        self.labelCuff.setObjectName("labelCuff")
        self.layoutValue.addWidget(self.labelCuff, 2, 0, 1, 1)
        self.TextBrowserCuff = QtWidgets.QTextBrowser(self.centralwidget)
        self.TextBrowserCuff.setMaximumSize(QtCore.QSize(200, 30))
        self.TextBrowserCuff.setObjectName("TextBrowserCuff")
        self.layoutValue.addWidget(self.TextBrowserCuff, 2, 1, 1, 1)
        self.labelSys = QtWidgets.QLabel(self.centralwidget)
        self.labelSys.setObjectName("labelSys")
        self.layoutValue.addWidget(self.labelSys, 3, 0, 1, 1)
        self.TextBrowserSys = QtWidgets.QTextBrowser(self.centralwidget)
        self.TextBrowserSys.setMaximumSize(QtCore.QSize(200, 30))
        self.TextBrowserSys.setObjectName("TextBrowserSys")
        self.layoutValue.addWidget(self.TextBrowserSys, 3, 1, 1, 1)
        self.labelMean = QtWidgets.QLabel(self.centralwidget)
        self.labelMean.setObjectName("labelMean")
        self.layoutValue.addWidget(self.labelMean, 4, 0, 1, 1)
        self.TextBrowserMean = QtWidgets.QTextBrowser(self.centralwidget)
        self.TextBrowserMean.setMaximumSize(QtCore.QSize(200, 30))
        self.TextBrowserMean.setObjectName("TextBrowserMean")
        self.layoutValue.addWidget(self.TextBrowserMean, 4, 1, 1, 1)
        self.labelDia = QtWidgets.QLabel(self.centralwidget)
        self.labelDia.setObjectName("labelDia")
        self.layoutValue.addWidget(self.labelDia, 5, 0, 1, 1)
        self.TextBrowserDia = QtWidgets.QTextBrowser(self.centralwidget)
        self.TextBrowserDia.setMaximumSize(QtCore.QSize(200, 30))
        self.TextBrowserDia.setObjectName("TextBrowserDia")
        self.layoutValue.addWidget(self.TextBrowserDia, 5, 1, 1, 1)
        self.labelHR = QtWidgets.QLabel(self.centralwidget)
        self.labelHR.setObjectName("labelHR")
        self.layoutValue.addWidget(self.labelHR, 6, 0, 1, 1)
        self.TextBrowserHR = QtWidgets.QTextBrowser(self.centralwidget)
        self.TextBrowserHR.setMaximumSize(QtCore.QSize(200, 30))
        self.TextBrowserHR.setObjectName("TextBrowserHR")
        self.layoutValue.addWidget(self.TextBrowserHR, 6, 1, 1, 1)
        self.labelRR = QtWidgets.QLabel(self.centralwidget)
        self.labelRR.setObjectName("labelRR")
        self.layoutValue.addWidget(self.labelRR, 7, 0, 1, 1)
        self.TextBrowserRR = QtWidgets.QTextBrowser(self.centralwidget)
        self.TextBrowserRR.setMaximumSize(QtCore.QSize(200, 30))
        self.TextBrowserRR.setObjectName("TextBrowserRR")
        self.layoutValue.addWidget(self.TextBrowserRR, 7, 1, 1, 1)
        self.labelST = QtWidgets.QLabel(self.centralwidget)
        self.labelST.setObjectName("labelST")
        self.layoutValue.addWidget(self.labelST, 8, 0, 1, 1)
        self.TextBrowserST = QtWidgets.QTextBrowser(self.centralwidget)
        self.TextBrowserST.setMaximumSize(QtCore.QSize(200, 30))
        self.TextBrowserST.setObjectName("TextBrowserST")
        self.layoutValue.addWidget(self.TextBrowserST, 8, 1, 1, 1)
        self.labelARR = QtWidgets.QLabel(self.centralwidget)
        self.labelARR.setMaximumSize(QtCore.QSize(112, 30))
        self.labelARR.setObjectName("labelARR")
        self.layoutValue.addWidget(self.labelARR, 9, 0, 1, 1)
        self.TextBrowserARR = QtWidgets.QTextBrowser(self.centralwidget)
        self.TextBrowserARR.setMaximumSize(QtCore.QSize(200, 30))
        self.TextBrowserARR.setObjectName("TextBrowserARR")
        self.layoutValue.addWidget(self.TextBrowserARR, 9, 1, 1, 1)
        self.labelTemp1 = QtWidgets.QLabel(self.centralwidget)
        self.labelTemp1.setObjectName("labelTemp1")
        self.layoutValue.addWidget(self.labelTemp1, 10, 0, 1, 1)
        self.TextBrowserTemp1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.TextBrowserTemp1.setMaximumSize(QtCore.QSize(200, 30))
        self.TextBrowserTemp1.setObjectName("TextBrowserTemp1")
        self.layoutValue.addWidget(self.TextBrowserTemp1, 10, 1, 1, 1)
        self.labelSPO2 = QtWidgets.QLabel(self.centralwidget)
        self.labelSPO2.setObjectName("labelSPO2")
        self.layoutValue.addWidget(self.labelSPO2, 0, 0, 1, 1)
        self.layoutValue.setColumnMinimumWidth(1, 1)
        self.layoutValue.setColumnStretch(1, 1)
        self.mainLayout.addLayout(self.layoutValue, 0, 0, 1, 1)
        self.layoutWidget = QtWidgets.QGridLayout()
        self.layoutWidget.setContentsMargins(0, 0, 0, 0)
        self.layoutWidget.setObjectName("layoutWidget")
        self.mainLayout.addLayout(self.layoutWidget, 0, 1, 4, 1)
        self.layoutECGLead = QtWidgets.QGridLayout()
        self.layoutECGLead.setObjectName("layoutECGLead")
        self.labelGroupName = QtWidgets.QLabel(self.centralwidget)
        self.labelGroupName.setObjectName("labelGroupName")
        self.layoutECGLead.addWidget(self.labelGroupName, 0, 3, 1, 3)
        self.labelV1 = QtWidgets.QLabel(self.centralwidget)
        self.labelV1.setObjectName("labelV1")
        self.layoutECGLead.addWidget(self.labelV1, 1, 0, 1, 1)
        self.labelV2 = QtWidgets.QLabel(self.centralwidget)
        self.labelV2.setObjectName("labelV2")
        self.layoutECGLead.addWidget(self.labelV2, 1, 1, 1, 1)
        self.labelV3 = QtWidgets.QLabel(self.centralwidget)
        self.labelV3.setObjectName("labelV3")
        self.layoutECGLead.addWidget(self.labelV3, 1, 2, 1, 1)
        self.labelV4 = QtWidgets.QLabel(self.centralwidget)
        self.labelV4.setObjectName("labelV4")
        self.layoutECGLead.addWidget(self.labelV4, 1, 3, 1, 1)
        self.labelV5 = QtWidgets.QLabel(self.centralwidget)
        self.labelV5.setObjectName("labelV5")
        self.layoutECGLead.addWidget(self.labelV5, 1, 4, 1, 1)
        self.labelV6 = QtWidgets.QLabel(self.centralwidget)
        self.labelV6.setObjectName("labelV6")
        self.layoutECGLead.addWidget(self.labelV6, 1, 5, 1, 1)
        self.labelLL = QtWidgets.QLabel(self.centralwidget)
        self.labelLL.setObjectName("labelLL")
        self.layoutECGLead.addWidget(self.labelLL, 1, 6, 1, 1)
        self.labelLA = QtWidgets.QLabel(self.centralwidget)
        self.labelLA.setObjectName("labelLA")
        self.layoutECGLead.addWidget(self.labelLA, 1, 7, 1, 1)
        self.labelRA = QtWidgets.QLabel(self.centralwidget)
        self.labelRA.setObjectName("labelRA")
        self.layoutECGLead.addWidget(self.labelRA, 1, 8, 1, 1)
        self.labelV1S = QtWidgets.QLabel(self.centralwidget)
        self.labelV1S.setObjectName("labelV1S")
        self.layoutECGLead.addWidget(self.labelV1S, 2, 0, 1, 1)
        self.labelV2S = QtWidgets.QLabel(self.centralwidget)
        self.labelV2S.setObjectName("labelV2S")
        self.layoutECGLead.addWidget(self.labelV2S, 2, 1, 1, 1)
        self.labelV3S = QtWidgets.QLabel(self.centralwidget)
        self.labelV3S.setObjectName("labelV3S")
        self.layoutECGLead.addWidget(self.labelV3S, 2, 2, 1, 1)
        self.labelV4S = QtWidgets.QLabel(self.centralwidget)
        self.labelV4S.setObjectName("labelV4S")
        self.layoutECGLead.addWidget(self.labelV4S, 2, 3, 1, 1)
        self.labelV5S = QtWidgets.QLabel(self.centralwidget)
        self.labelV5S.setObjectName("labelV5S")
        self.layoutECGLead.addWidget(self.labelV5S, 2, 4, 1, 1)
        self.labelV6S = QtWidgets.QLabel(self.centralwidget)
        self.labelV6S.setObjectName("labelV6S")
        self.layoutECGLead.addWidget(self.labelV6S, 2, 5, 1, 1)
        self.labelLLS = QtWidgets.QLabel(self.centralwidget)
        self.labelLLS.setObjectName("labelLLS")
        self.layoutECGLead.addWidget(self.labelLLS, 2, 6, 1, 1)
        self.labelLAS = QtWidgets.QLabel(self.centralwidget)
        self.labelLAS.setObjectName("labelLAS")
        self.layoutECGLead.addWidget(self.labelLAS, 2, 7, 1, 1)
        self.labelRAS = QtWidgets.QLabel(self.centralwidget)
        self.labelRAS.setObjectName("labelRAS")
        self.layoutECGLead.addWidget(self.labelRAS, 2, 8, 1, 1)
        self.mainLayout.addLayout(self.layoutECGLead, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(318, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.layoutButtonAndPar = QtWidgets.QGridLayout()
        self.layoutButtonAndPar.setContentsMargins(2, 2, 2, 2)
        self.layoutButtonAndPar.setObjectName("layoutButtonAndPar")
        self.layoutPar = QtWidgets.QGridLayout()
        self.layoutPar.setObjectName("layoutPar")
        self.btnSer = QtWidgets.QPushButton(self.centralwidget)
        self.btnSer.setMaximumSize(QtCore.QSize(135, 30))
        self.btnSer.setObjectName("btnSer")
        self.layoutPar.addWidget(self.btnSer, 0, 0, 1, 1)
        self.textEditSer = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditSer.setMaximumSize(QtCore.QSize(180, 30))
        self.textEditSer.setObjectName("textEditSer")
        self.layoutPar.addWidget(self.textEditSer, 0, 1, 1, 1)
        self.labelAdjust = QtWidgets.QLabel(self.centralwidget)
        self.labelAdjust.setObjectName("labelAdjust")
        self.layoutPar.addWidget(self.labelAdjust, 1, 0, 1, 1)
        self.comboAdjust = QtWidgets.QComboBox(self.centralwidget)
        self.comboAdjust.setObjectName("comboAdjust")
        self.layoutPar.addWidget(self.comboAdjust, 1, 1, 1, 1)
        self.labelBPModel = QtWidgets.QLabel(self.centralwidget)
        self.labelBPModel.setObjectName("labelBPModel")
        self.layoutPar.addWidget(self.labelBPModel, 2, 0, 1, 1)
        self.comboBPModel = QtWidgets.QComboBox(self.centralwidget)
        self.comboBPModel.setObjectName("comboBPModel")
        self.layoutPar.addWidget(self.comboBPModel, 2, 1, 1, 1)
        self.labelBloodPre = QtWidgets.QLabel(self.centralwidget)
        self.labelBloodPre.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelBloodPre.setObjectName("labelBloodPre")
        self.layoutPar.addWidget(self.labelBloodPre, 3, 0, 1, 1)
        self.spinBoxBP = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxBP.setObjectName("spinBoxBP")
        self.layoutPar.addWidget(self.spinBoxBP, 3, 1, 1, 1)
        self.labelECG = QtWidgets.QLabel(self.centralwidget)
        self.labelECG.setObjectName("labelECG")
        self.layoutPar.addWidget(self.labelECG, 4, 0, 1, 1)
        self.comboECGModel = QtWidgets.QComboBox(self.centralwidget)
        self.comboECGModel.setObjectName("comboECGModel")
        self.layoutPar.addWidget(self.comboECGModel, 4, 1, 1, 1)
        self.labelECGGain = QtWidgets.QLabel(self.centralwidget)
        self.labelECGGain.setObjectName("labelECGGain")
        self.layoutPar.addWidget(self.labelECGGain, 5, 0, 1, 1)
        self.comboECGGain = QtWidgets.QComboBox(self.centralwidget)
        self.comboECGGain.setObjectName("comboECGGain")
        self.layoutPar.addWidget(self.comboECGGain, 5, 1, 1, 1)
        self.labelRespGain = QtWidgets.QLabel(self.centralwidget)
        self.labelRespGain.setObjectName("labelRespGain")
        self.layoutPar.addWidget(self.labelRespGain, 6, 0, 1, 1)
        self.comboRespGain = QtWidgets.QComboBox(self.centralwidget)
        self.comboRespGain.setObjectName("comboRespGain")
        self.layoutPar.addWidget(self.comboRespGain, 6, 1, 1, 1)
        self.layoutButtonAndPar.addLayout(self.layoutPar, 0, 0, 1, 1)
        self.layoutButton = QtWidgets.QGridLayout()
        self.layoutButton.setObjectName("layoutButton")
        self.btnSPO2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnSPO2.setMaximumSize(QtCore.QSize(100, 30))
        self.btnSPO2.setObjectName("btnSPO2")
        self.layoutButton.addWidget(self.btnSPO2, 0, 0, 1, 1)
        self.btnTemp = QtWidgets.QPushButton(self.centralwidget)
        self.btnTemp.setMaximumSize(QtCore.QSize(100, 30))
        self.btnTemp.setObjectName("btnTemp")
        self.layoutButton.addWidget(self.btnTemp, 0, 1, 1, 1)
        self.btnBloodPre = QtWidgets.QPushButton(self.centralwidget)
        self.btnBloodPre.setMaximumSize(QtCore.QSize(100, 30))
        self.btnBloodPre.setObjectName("btnBloodPre")
        self.layoutButton.addWidget(self.btnBloodPre, 0, 2, 1, 1)
        self.btnECG = QtWidgets.QPushButton(self.centralwidget)
        self.btnECG.setMaximumSize(QtCore.QSize(100, 30))
        self.btnECG.setObjectName("btnECG")
        self.layoutButton.addWidget(self.btnECG, 1, 0, 1, 1)
        self.btnV6 = QtWidgets.QPushButton(self.centralwidget)
        self.btnV6.setMaximumSize(QtCore.QSize(100, 30))
        self.btnV6.setObjectName("btnV6")
        self.layoutButton.addWidget(self.btnV6, 1, 1, 1, 1)
        self.btnResp = QtWidgets.QPushButton(self.centralwidget)
        self.btnResp.setMaximumSize(QtCore.QSize(100, 30))
        self.btnResp.setObjectName("btnResp")
        self.layoutButton.addWidget(self.btnResp, 1, 2, 1, 1)
        self.layoutButtonAndPar.addLayout(self.layoutButton, 1, 0, 1, 1)
        self.mainLayout.addLayout(self.layoutButtonAndPar, 3, 0, 1, 1)
        self.mainLayout.setColumnStretch(1, 1)
        self.verticalLayout.addLayout(self.mainLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1266, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PM1200 监护仪"))
        self.labelPR.setText(_translate("MainWindow", "脉率"))
        self.labelCuff.setText(_translate("MainWindow", "袖带压力"))
        self.labelSys.setText(_translate("MainWindow", "收缩压"))
        self.labelMean.setText(_translate("MainWindow", "平均压"))
        self.labelDia.setText(_translate("MainWindow", "舒张压"))
        self.labelHR.setText(_translate("MainWindow", "心率"))
        self.labelRR.setText(_translate("MainWindow", "呼吸率"))
        self.labelST.setText(_translate("MainWindow", "ST电位(mV)"))
        self.labelARR.setText(_translate("MainWindow", "心律异常代码"))
        self.labelTemp1.setText(_translate("MainWindow", "体温"))
        self.labelSPO2.setText(_translate("MainWindow", "血氧饱和度"))
        self.labelGroupName.setText(_translate("MainWindow", "   心电导联状态"))
        self.labelV1.setText(_translate("MainWindow", " V1"))
        self.labelV2.setText(_translate("MainWindow", " V2"))
        self.labelV3.setText(_translate("MainWindow", " V3"))
        self.labelV4.setText(_translate("MainWindow", " V4"))
        self.labelV5.setText(_translate("MainWindow", " V5"))
        self.labelV6.setText(_translate("MainWindow", " V6"))
        self.labelLL.setText(_translate("MainWindow", " LL"))
        self.labelLA.setText(_translate("MainWindow", " LA"))
        self.labelRA.setText(_translate("MainWindow", " RA"))
        self.labelV1S.setText(_translate("MainWindow", "未接"))
        self.labelV2S.setText(_translate("MainWindow", "未接"))
        self.labelV3S.setText(_translate("MainWindow", "未接"))
        self.labelV4S.setText(_translate("MainWindow", "未接"))
        self.labelV5S.setText(_translate("MainWindow", "未接"))
        self.labelV6S.setText(_translate("MainWindow", "未接"))
        self.labelLLS.setText(_translate("MainWindow", "未接"))
        self.labelLAS.setText(_translate("MainWindow", "未接"))
        self.labelRAS.setText(_translate("MainWindow", "未接"))
        self.btnSer.setText(_translate("MainWindow", "打开串口："))
        self.labelAdjust.setText(_translate("MainWindow", "Adjust:"))
        self.labelBPModel.setText(_translate("MainWindow", "血压测量模式:"))
        self.labelBloodPre.setText(_translate("MainWindow", "袖带预充气(mmHg):"))
        self.labelECG.setText(_translate("MainWindow", "心电测量模式:"))
        self.labelECGGain.setText(_translate("MainWindow", "心电波形增益:"))
        self.labelRespGain.setText(_translate("MainWindow", "呼吸波形增益:"))
        self.btnSPO2.setText(_translate("MainWindow", "血氧(OFF)"))
        self.btnTemp.setText(_translate("MainWindow", "体温(OFF)"))
        self.btnBloodPre.setText(_translate("MainWindow", "血压(OFF)"))
        self.btnECG.setText(_translate("MainWindow", "心电(OFF)"))
        self.btnV6.setText(_translate("MainWindow", "V6(ON)"))
        self.btnResp.setText(_translate("MainWindow", "Resp(OFF)"))

        #部件属性设置
    def SettingComponentProperties(self):
        self.textEditSer.setPlainText('/dev/ttyACM0')

        self.boxMessage = QtWidgets.QMessageBox()

        #Widget窗口布局
        self.pw1 = pg.PlotWidget()
        self.layoutWidget.addWidget(self.pw1,0,0)

        self.pwV1 = pg.PlotWidget()
        self.layoutWidget.addWidget(self.pwV1,0,1)

        self.pw2 = pg.PlotWidget()
        self.layoutWidget.addWidget(self.pw2,1,0)

        self.pwV2 = pg.PlotWidget()
        self.layoutWidget.addWidget(self.pwV2,1,1)

        self.pw3 = pg.PlotWidget()
        self.layoutWidget.addWidget(self.pw3,2,0)

        self.pwV3 = pg.PlotWidget()
        self.layoutWidget.addWidget(self.pwV3,2,1)

        self.pwaVR = pg.PlotWidget()
        self.layoutWidget.addWidget(self.pwaVR,3,0)

        self.pwV4 = pg.PlotWidget()
        self.layoutWidget.addWidget(self.pwV4,3,1)

        self.pwaVL = pg.PlotWidget()
        self.layoutWidget.addWidget(self.pwaVL,4,0)

        self.pwV5 = pg.PlotWidget()
        self.layoutWidget.addWidget(self.pwV5,4,1)

        self.pwaVF = pg.PlotWidget()
        self.layoutWidget.addWidget(self.pwaVF,5,0)

        self.pwV6 = pg.PlotWidget()
        self.layoutWidget.addWidget(self.pwV6,5,1)

        self.pwResp = pg.PlotWidget()
        self.layoutWidget.addWidget(self.pwResp,6,0)

        self.pwSPO2 = pg.PlotWidget()
        self.layoutWidget.addWidget(self.pwSPO2,6,1)

        #pwSPO2.setLabel('left', 'Amplitude', units='')
        #pwSPO2.setLabel('bottom', 'Time', units='s')
        self.pwSPO2.setTitle('血氧波形')
        self.pwSPO2.setXRange(0, 200)
        self.pwSPO2.setYRange(0, 100)

        self.pw1.setTitle('心电波形1')
        self.pw1.setXRange(0, 1000)
        self.pw1.setYRange(0, 250)

        self.pw2.setTitle('心电波形2')
        self.pw2.setXRange(0, 1200)
        self.pw2.setYRange(0, 250)

        self.pw3.setTitle('心电波形3')
        self.pw3.setXRange(0, 1200)
        self.pw3.setYRange(0, 250)

        self.pwV1.setTitle('心电波形V1')
        self.pwV1.setXRange(0, 1200)
        self.pwV1.setYRange(0, 250)

        self.pwV2.setTitle('心电波形V2')
        self.pwV2.setXRange(0, 1200)
        self.pwV2.setYRange(0, 250)

        self.pwV3.setTitle('心电波形V3')
        self.pwV3.setXRange(0, 1200)
        self.pwV3.setYRange(0, 250)

        self.pwV4.setTitle('心电波形V4')
        self.pwV4.setXRange(0, 1200)
        self.pwV4.setYRange(0, 250)

        self.pwV5.setTitle('心电波形V5')
        self.pwV5.setXRange(0, 1200)
        self.pwV5.setYRange(0, 250)

        self.pwV6.setTitle('心电波形V6')
        self.pwV6.setXRange(0, 1200)
        self.pwV6.setYRange(0, 250)

        self.pwaVL.setTitle('心电波形aVL')
        self.pwaVL.setXRange(0, 1200)
        self.pwaVL.setYRange(0, 250)

        self.pwaVR.setTitle('心电波形aVR')
        self.pwaVR.setXRange(0, 1200)
        self.pwaVR.setYRange(0, 250)

        self.pwaVF.setTitle('心电波形aVF')
        self.pwaVF.setXRange(0, 1200)
        self.pwaVF.setYRange(0, 250)

        self.pwResp.setTitle('呼吸波形Resp')
        self.pwResp.setXRange(0, 1200)
        self.pwResp.setYRange(0, 250)

        self.comboAdjust.addItem("静态压力校准")
        self.comboAdjust.addItem("静态压力偏差设置")
        self.comboAdjust.addItem("温度1偏差设置")
        self.comboAdjust.addItem("漏气检测")

        self.spinBoxBP.setMaximum(300)
        self.spinBoxBP.setValue(170)
        self.spinBoxBP.setMinimum(40)
        self.spinBoxBP.setSingleStep(10)

        self.comboBPModel.addItem("成人模式")
        self.comboBPModel.addItem("儿童模式")
        self.comboBPModel.addItem("新生儿模式")

        self.comboECGModel.addItem("手术模式")
        self.comboECGModel.addItem("监护模式")
        self.comboECGModel.addItem("诊断模式")
        self.comboECGModel.setCurrentIndex(1)

        self.comboECGGain.addItem("x0.25")
        self.comboECGGain.addItem("x0.5")
        self.comboECGGain.addItem("x1")
        self.comboECGGain.addItem("x2")
        self.comboECGGain.setCurrentIndex(2)

        self.comboRespGain.addItem("x0.25")
        self.comboRespGain.addItem("x0.5")
        self.comboRespGain.addItem("x1")
        self.comboRespGain.addItem("x2")
        self.comboRespGain.setCurrentIndex(2)

    #参数更新
    def TextBrowserUpdate(self):
        self.TextBrowserSPO2.setText(PMPar.measureValue[0][1])
        self.TextBrowserPR.setText(PMPar.measureValue[1][1])
        self.TextBrowserCuff.setText(PMPar.measureValue[2][1])
        self.TextBrowserSys.setText(PMPar.measureValue[3][1])
        self.TextBrowserMean.setText(PMPar.measureValue[4][1])
        self.TextBrowserDia.setText(PMPar.measureValue[5][1])
        self.TextBrowserHR.setText(PMPar.measureValue[6][1])
        self.TextBrowserRR.setText(PMPar.measureValue[7][1])
        self.TextBrowserST.setText(PMPar.measureValue[8][1])
        self.TextBrowserARR.setText(PMPar.measureValue[9][1])
        self.TextBrowserTemp1.setText(PMPar.measureValue[10][1])
        #self.TextBrowserTemp2.setText(PMPar.measureValue[11][1])

    #心电导联状态更新
    def LabelLeadUpdate(self, V1, V2, V3, V4, V5, V6, LL, LA, RA):
        print(V1, V2, V3, V4, V5, V6, LL, LA, RA)
        if(V1):
            self.labelV1S.setText("脱落")
        else:
            self.labelV1S.setText("正常")
        if(V2):
            self.labelV2S.setText("脱落")
        else:
            self.labelV2S.setText("正常")
        if(V3):
            self.labelV3S.setText("脱落")
        else:
            self.labelV3S.setText("正常")
        if(V4):
            self.labelV4S.setText("脱落")
        else:
            self.labelV4S.setText("正常")
        if(V5):
            self.labelV5S.setText("脱落")
        else:
            self.labelV5S.setText("正常")
        if(V6):
            self.labelV6S.setText("脱落")
        else:
            self.labelV6S.setText("正常")
        if(LL):
            self.labelLLS.setText("脱落")
        else:
            self.labelLLS.setText("正常")
        if(LA):
            self.labelLAS.setText("脱落")
        else:
            self.labelLAS.setText("正常")
        if(RA):
            self.labelRAS.setText("脱落")
        else:
            self.labelRAS.setText("正常")
